### PR TITLE
Issue 1873 custom message metric feature

### PR DESCRIPTION
**Pull request by SpencerWightman**
## What

I added a `'custom message'` metric to the existing [Custom Metrics API](https://www.artillery.io/docs/reference/extension-apis#custom-metrics-api) that catches a processor file's `'custom message'` emit. It displays each custom message from the time period in the period report on separate lines. This was done to address issue #1873.

Screenshot 2023-12-04 at 3 12 28 PM

## Why

In some cases users want to add custom messages/data to the period reports. Two people in the issue thread plus myself expressed a desire for the feature. Furthermore, @bernardobridge added the `enhancement` label to the issue.

## How

In summary, the `'custom message'` metric was added by integrating it with the current Custom Metrics API implementation flow, primarily in `SSMS.js`, `runner.js`, and `console-reporter.js`. It used the other custom metric implementations as a template.

## Testing

I added a test to `artillery/test/unit/ssms.basic.test.js` for the `customMessage` metric, alongside the tests for the other metrics. All the tests in `ssms.basic.test.js` passed after my addition. All the tests in `artillery/test/runner.sh` passed except for the 2nd and 3rd. However, those tests also failed when run on branch main. All of the `./run.sh` tests in `packages/core` passed.

### CODE REVIEW

**Comment by hassy** [comment]
Thanks for taking the time @SpencerWightman! I'd love to understand the exact use case of something like this, e.g. what type of information would be particularly useful to have attached to a specific time period.

**Comment by SpencerWightman** [comment]
No problem at all @hassy. Artillery is awesome and I’m happy to contribute!

At a high level, the use case is when a developer extracts scenario logic to a JS file and wants to log data from that file.

Extracting scenario logic can occur because a developer finds it necessary ([mixing engines](https://github.com/artilleryio/artillery/issues/1005) in the same scenario, for example) or because they find implementing a complex scenario in JS preferable. Logged data can include response bodies, headers, WebSocket emitted data, UUIDs, or any other data, either raw or after helper function processing.

The `customMessage` feature, implemented through the Custom Metrics API, is simpler and more flexible than storing `function` action values with `context.vars` and then using `- log: "{{ name }}"` in the YAML:

1. Emitting within the JS file allows developers to easily create as many messages as they want, exactly where they want in the code, per virtual user. Example: a value changes through an iterative process or based on a conditional, and the developer wants to log the value selectively, perhaps along with a precise timestamp or other ancillary data. This would be cumbersome or impossible with the `context.vars` system because 1) `- log: "{{ name }}"` always logs a value and 2) `context.vars.name` is always the latest `name` value.

2. Using `context.vars` in JS to log values from the YAML file, then adding logs to the YAML, is less straightforward than having logging logic in the JS file along with the rest of the scenario code (especially if there are many values to log). The `customMessage` feature requires less code, and the code is in one file.

3. Messages logged through the `context.vars` system are not within a period report and are more difficult to parse in the overall output as a result. Logging within a period report is also desirable for clear alignment with testing periods.

In summary, the option to output custom period report data from a JS file means more control and convenience in complex testing situations.

I’m happy to elaborate if any of that is too vague!

**Comment by SpencerWightman** [comment]
Hi @hassy, is there anything I can do to move this forward? This feature adds intuitive custom messaging for developers. The code integrates smoothly into the Custom Metrics API and has a test.

**Comment by hassy** [comment]
Hi @SpencerWightman, apologies for the delay. Agree that a way to associate a text log with a specific time period may be useful, but the implementation should not be via the metrics API. Using a `counter` metric as already available would provide essentially the same functionality as the implementation in this PR. We'll look at supporting time-specific logs at some point, but it's not a priority right now. Thank you for taking the time, and apologies again for the delay.

**Pull request closed without merging**
