### PR TITLE
fix(core): import mjs path correctly when running on windows

### PR DESCRIPTION
**Pull request by thrandale**
This fixes issue #2661

### CODE REVIEW

**Comment by hassy** [comment]
thanks @thrandale! Is the issue due to a missing relative path? ie. in your example `./artilleryRunner.mjs` should work as expected (if the MJS file is in the same directory as the YAML script). There's a test for loading ESM here, would you mind updating that please? https://github.com/artilleryio/artillery/blob/242a7964934851bf77e53eebf44e6312de723663/packages/artillery/test/cli/async-hooks-esm.test.js#L10

**Comment by thrandale** [comment]
@hassy Even using a relative path, it still fails with the same error. It is odd that it is not failing in the CI. I believe this is only an issue on Windows. Does the CI run the windows tests?

**Comment by ggecy** [comment]
> @hassy Even using a relative path, it still fails with the same error. When it does the `path.resolve()`, that resolve either an absolute or relative path to an absolute path. It is odd that it is not failing in the CI. I believe this is only an issue on Windows. Does the CI run the windows tests?

I can confirm this - we have this problem only on windows, I can run on macos without error.

**Comment by bernardobridge** [comment]
Hi @thrandale 👋 ! Thanks for the contribution. We have now added windows tests to CI, so we could confirm fixes like this.

I've opened https://github.com/artilleryio/artillery/pull/3293 with your fix and ran our full suite against it, and it seems to work 👍 . If you want to rebase this branch against `main`, I can close my PR and merge this one once the test suite runs here too. If you do that in the next couple of days (as we aim to release on Monday), I'll use your PR. Otherwise I'll use my PR and reference you in the release anyway.

Thanks again!

**Comment by thrandale** [comment]
Thanks @bernardobridge. I have rebased my branch off `main`.

**Comment by bernardobridge** [comment]
Hi @thrandale, thanks for that. I'm merging this as the tests as passing (they appear red, but it's a bug that happens when running against contributor PR's).

Thanks again for the fix! It'll be out in 2.0.19 next week.

**Pull request merged**
