### PR TITLE
feat: add capture support to ws engine

### LINKED ISSUE #800: Capture response from websocket using engine:ws
```
config:
  target: "ws://localhost:8080/4h4j4kl4n4j4h4k4k4j4h4j/8d7g8g9f87d7d988f8b9f8b?userId=QvHPh7NXWz"
  processor: "./load-test.js"
  phases:
    - duration: 6
      arrivalRate: 1
      rampTo: 10
      name: "Ramping up the load"

    - duration: 6
      arrivalRate: 10
      rampTo: 10
      name: "Pushing a constant load"

scenarios:
  - engine: "ws"
    flow:
      - function: "autheticationDetails"
      - send:
          type: "authenticate"
          attendee: "{{ attendee }}"
          token: "{{ token }}"
      - think: 5
      - send:
          type: "open_channel"
          participants: ""
      - think: 5
      - send:
          type: "send_message"
          channel: "5e3d6b72ab7f55516e3b34f4"
          body: { type: 'text', text: '==============Test==================' }
```
**While sending this message receives this response respectively.**

Message:` {"type": "open_channel","participants": ""}`
Response: `{"type":"channel","channel":"5e3d6b72ab7f55516e3b34f4","created":false}`

> Cannot capture channel from response and pass it to next request?

### PR DESCRIPTION
**Pull request by deyceg**
Fixes #800. Retains backwards compatibility with existing send api and will support existing capture api too.

### CODE REVIEW

**Comment by deyceg** [comment]
@hassy looking to get some feedback on this soonish. We need to load test a WebRTC signalling server over web sockets and most tools were limited in one way or another. A solution that allows us to write test scripts in ES6 is preferrable as alot of the exist client-side code is written for the browser!

**Comment by hassy** [comment]
Thank you for the PR @deyceg! 

A public roadmap is something I'm hoping to have in place soon. The main outstanding item for a 2.0 pre-release is a refactoring of the metrics store, which is in active development.

**Comment by kevin96666** [comment]
Hello @deyceg 
Thanks for the feature.
How is it working (regarding the yaml conf) ?

**Comment by deyceg** [comment]
> Hello @deyceg
> Thanks for the feature.
> How is it working (regarding the yaml conf) ?

@kevin96666 

The API maintains backwards compatibility with the old api and existing capture apis!

Heres my example (load testing webrtc signalling server):

```
config:
  target: "wss://foo/bar
  processor: "./utils.js"
  phases:
    - duration: 300
      arrivalRate: 5
      rampTo: 100
  ws:
    subprotocols:
      - janus-protocol
scenarios:
  - engine: "ws"
    flow:
      - function: "generateTransactionId"
      - send:
          payload:
            janus: create
            transaction: "{{ transactionId }}"
          capture:
            json: "$.data.id"
            as: "id"
      - think: 1
      - send:
          janus: attach
          plugin: "janus.plugin.videoroom"
          opaque_id: "videoroomtest-{{ transactionId }}"
          transaction: "{{ transactionId }}"
          session_id: "{{ id }}"
      - think: 1
      - loop:
        - send:
            janus: keepalive
            session_id: "{{ id }}"
            transaction: "{{ transactionId }}"
        - think: 25
        count: 10
```

**Comment by buildscientist** [comment]
@hassy Is this feature earmarked for being merged into the 1.x line of code at all or is it only bound for the 2.x release? Thanks.

**Comment by simonbuehler** [comment]
hi,

great feature but i get this, what am i doing wrong here?


```
DEBUG=ws c:/Users/User/node_modules/artillery/bin/artillery run test.yaml

ARTILLERY DEV PREVIEW �
Please report bugs on https://github.com/artilleryio/artillery/issues

Artillery running - 2021-04-01T10:36:21.890Z

Phase started: unnamed (index: 0, duration: 1s) 12:36:22(+0200)

.   ws WS send: {"event":"pusher:subscribe","data":{"channel":"test"}} +0ms
  ws WS receive: {"event":"pusher:connection_established","data":"{\"socket_id\":\"829801229.295977059\",\"activity_timeout\":30}"} +2ms
  ws captures and matches: +3ms
  ws {} +1ms
  ws {
  ws   test: {
  ws     value: {
  ws       event: 'pusher:connection_established',
  ws       data: '{"socket_id":"829801229.295977059","activity_timeout":30}'
  ws     },
  ws     strict: undefined,
  ws     failed: false
  ws   }
  ws } +1ms
c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:76
    let payload = template(params.capture ? params.payload : params, context);
                                  ^

TypeError: Cannot read property 'capture' of undefined
    at f (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:76:35)
    at fn (c:\Users\User\node_modules\async\lib\async.js:746:34)
    at c:\Users\User\node_modules\async\lib\async.js:1213:16
    at c:\Users\User\node_modules\async\lib\async.js:166:37
    at c:\Users\User\node_modules\async\lib\async.js:706:43
    at c:\Users\User\node_modules\async\lib\async.js:167:37
    at c:\Users\User\node_modules\async\lib\async.js:1209:30
    at captured (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:144:18)
    at c:\Users\User\node_modules\artillery\core\lib\engine_util.js:470:16
    at c:\Users\User\node_modules\async\lib\async.js:52:16
```

with this 

```yaml
config:
  target: "ws://grabber.test:6001/app/mykey?protocol=7&client=js&version=4.4.0&flash=false"
  phases:
    - duration: 1
      arrivalRate: 1
scenarios:
  - engine: ws
    flow:
      - send:
          payload: '{"event":"pusher:subscribe","data":{"channel":"test"}}'
          capture:
            - json: "$"
              as: "test"
      - log: "check 1 2"
      - think: 10
```

**Comment by simonbuehler** [comment]
rather strange:

when adding a 
``` js
console.log("dump " + params);
```
in line 71 of engine_ws.js
the following outouts gets shown
``` 
. dump [object Object]
dump undefined
```

why twice?

**Comment by hassy** [comment]
@simonbuehler strange indeed! I'll take a 👀 

Kudos for being on the bleeding edge with 2.0 dev release!😄

**Comment by simonbuehler** [comment]
@hassy did't you already find the time to look into this?

**Comment by simonbuehler** [comment]
added a trace for debugging the double called issue, where in the second call the `params` parameter in https://github.com/artilleryio/artillery/blob/7e684b2fc23bf89660c1736a0b4a1008f9094a77/core/lib/engine_ws.js#L70 is undefined

```js
λ DEBUG=ws c:/Users/User/node_modules/artillery/bin/artillery run test.yaml                                                                  
                                                                                                                                             
ARTILLERY DEV PREVIEW �                                                                                                                      
Please report bugs on https://github.com/artilleryio/artillery/issues                                                                        
                                                                                                                                             
Artillery running - 2021-05-11T09:25:57.480Z                                                                                                 
                                                                                                                                             
Phase started: unnamed (index: 0, duration: 5s) 11:25:57(+0200)                                                                              
                                                                                                                                             
 {                                                                                                                                           
  payload: '{"event":"pusher:subscribe","data":{"channel":"test"}}',                                                                         
  capture: { json: '$', as: 'test' }                                                                                                         
}                                                                                                                                            
Trace                                                                                                                                        
    at f (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:74:13)                                                                  
    at fn (c:\Users\User\node_modules\async\lib\async.js:746:34)                                                                             
    at c:\Users\User\node_modules\async\lib\async.js:1213:16                                                                                 
    at c:\Users\User\node_modules\async\lib\async.js:166:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:706:43                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:167:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:1209:30                                                                                 
    at WebSocket.<anonymous> (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:196:16)                                             
    at WebSocket.emit (events.js:315:20)                                                                                                     
    at WebSocket.setSocket (c:\Users\User\node_modules\ws\lib\websocket.js:151:10)                                                           
  ws WS send: {"event":"pusher:subscribe","data":{"channel":"test"}} +0ms                                                                    
  ws WS receive: {"event":"pusher:connection_established","data":"{\"socket_id\":\"773296592.932245740\",\"activity_timeout\":30}"} +2ms     
  ws captures and matches: +3ms                                                                                                              
  ws {} +1ms                                                                                                                                 
  ws {                                                                                                                                       
  ws   test: {                                                                                                                               
  ws     value: {                                                                                                                            
  ws       event: 'pusher:connection_established',                                                                                           
  ws       data: '{"socket_id":"773296592.932245740","activity_timeout":30}'                                                                 
  ws     },                                                                                                                                  
  ws     strict: undefined,                                                                                                                  
  ws     failed: false                                                                                                                       
  ws   }                                                                                                                                     
  ws } +1ms                                                                                                                                  
undefined                                                                                                                                    
Trace                                                                                                                                        
    at f (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:74:13)                                                                  
    at fn (c:\Users\User\node_modules\async\lib\async.js:746:34)                                                                             
    at c:\Users\User\node_modules\async\lib\async.js:1213:16                                                                                 
    at c:\Users\User\node_modules\async\lib\async.js:166:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:706:43                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:167:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:1209:30                                                                                 
    at captured (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:145:18)                                                          
    at c:\Users\User\node_modules\artillery\core\lib\engine_util.js:470:16                                                                   
    at c:\Users\User\node_modules\async\lib\async.js:52:16                                                                                   
c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:77                                                                                
    let payload = template(params.capture ? params.payload : params, context);                                                               
                                  ^                                                                                                          
                                                                                                                                             
TypeError: Cannot read property 'capture' of undefined                                                                                       
    at f (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:77:35)                                                                  
    at fn (c:\Users\User\node_modules\async\lib\async.js:746:34)                                                                             
    at c:\Users\User\node_modules\async\lib\async.js:1213:16                                                                                 
    at c:\Users\User\node_modules\async\lib\async.js:166:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:706:43                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:167:37                                                                                  
    at c:\Users\User\node_modules\async\lib\async.js:1209:30                                                                                 
    at captured (c:\Users\User\node_modules\artillery\core\lib\engine_ws.js:145:18)                                                          
    at c:\Users\User\node_modules\artillery\core\lib\engine_util.js:470:16                                                                   
    at c:\Users\User\node_modules\async\lib\async.js:52:16                                                                                   
```

**Comment by simonbuehler** [comment]
seems related / fixed by #1021 i must test it though

**Comment by simonbuehler** [comment]
@deyceg does this also support capturing the inital response of a ws connection after connecting ? ( e.g. pusher sending 

```
{"event":"pusher:connection_established","data":"{\"socket_id\":\"914817366.606011998\",\"activity_timeout\":30}"}
```

without a message beeing sent from the client ?

**Comment by karolinadebowska** [comment]
@hassy any update? I need this feature asap.

**Comment by AdrKacz** [comment]
Hi,

I have a question concerning this PR 😊 When using a *WebSocket*, multiple VUs are connected to the same channel. So I can received a message (and thus capturing it) that I am not interested in (coming from another VU).

Is it possible to coupled this feature with a *function* that waits until the desire message is received by the **WebSocket** and only after captures/processes it?

**Comment by AdrKacz** [comment]
After reading the code, I've seen an easy update to be able to add a custom *message handler*. Unfortunately, I've never contributed to this project, so I don't know what I am suppose to do.

I've written what I was thinking about below.

# Add a custom handler

## `artillery/core/lib/engine_ws.js`

```js
// ...
function getMessageHandler(context, params, ee, callback) {
  if (params.capture.handler !== undefined) {
    const done = () => callback(null, context)
    const error = (err) => callback(err, null)
     // don't know where to get config now, but you get the idea
    return (event) => (config.processor[params.capture.handler](event, error, done))
  } else {
    return function messageHandler(event) {
      // ... (don't change anything here)
    }
  }
}
// ...
```

# Update your files for custom handler

## YAML

```yaml
# ...
send:
  payload: "{{ getPayload }}"
  capture:
    handler: "{{ handler }} "
# ...
```

## JS

```js
function handler (event, error, done) {
  // do whatever you want
  // ...
  if (yourSuperbCondition) {
    done() // that will give back control to the next step
  }
}
``` 


*PS: I apologise for this ugly message, let me know how what I should too to help or if my message is inappropriate*

**Comment by code-leen** [comment]
> 

Did you edit the `getMessageHandler` directly? Or did you import and modify the WS engine?

**Comment by code-leen** [comment]
> After reading the code, I've seen an easy update to be able to add a custom _message handler_. Unfortunately, I've never contributed to this project, so I don't know what I am suppose to do.
> 
> I've written what I was thinking about below.
> 
> # Add a custom handler
> ## `artillery/core/lib/engine_ws.js`
> ```js
> // ...
> function getMessageHandler(context, params, ee, callback) {
>   if (params.capture.handler !== undefined) {
>     const done = () => callback(null, context)
>     const error = (err) => callback(err, null)
>      // don't know where to get config now, but you get the idea
>     return (event) => (config.processor[params.capture.handler](event, error, done))
>   } else {
>     return function messageHandler(event) {
>       // ... (don't change anything here)
>     }
>   }
> }
> // ...
> ```
> 
> # Update your files for custom handler
> ## YAML
> ```yaml
> # ...
> send:
>   payload: "{{ payload }}"
>   capture:
>     handler: "handler"
> # ...
> ```
> 
> ## JS
> ```js
> function handler (event, error, done) {
>   // do whatever you want
>   // ...
>   if (yourSuperbCondition) {
>     done() // that will give back control to the next step
>   }
> }
> ```
> 
> _PS: I apologise for this ugly message, let me know how what I should too to help or if my message is inappropriate_
> 
> ### Edit
> _I've tested it and it works as intended_

Did you edit the `getMessageHandler` directly? Or did you import and modify the WS engine?

**Comment by code-leen** [comment]
> After reading the code, I've seen an easy update to be able to add a custom _message handler_. Unfortunately, I've never contributed to this project, so I don't know what I am suppose to do.
> 
> I've written what I was thinking about below.
> 
> # Add a custom handler
> ## `artillery/core/lib/engine_ws.js`
> ```js
> // ...
> function getMessageHandler(context, params, ee, callback) {
>   if (params.capture.handler !== undefined) {
>     const done = () => callback(null, context)
>     const error = (err) => callback(err, null)
>      // don't know where to get config now, but you get the idea
>     return (event) => (config.processor[params.capture.handler](event, error, done))
>   } else {
>     return function messageHandler(event) {
>       // ... (don't change anything here)
>     }
>   }
> }
> // ...
> ```
> 
> # Update your files for custom handler
> ## YAML
> ```yaml
> # ...
> send:
>   payload: "{{ payload }}"
>   capture:
>     handler: "handler"
> # ...
> ```
> 
> ## JS
> ```js
> function handler (event, error, done) {
>   // do whatever you want
>   // ...
>   if (yourSuperbCondition) {
>     done() // that will give back control to the next step
>   }
> }
> ```
> 
> _PS: I apologise for this ugly message, let me know how what I should too to help or if my message is inappropriate_
> 
> ### Edit
> _I've tested it and it works as intended_

@AdrKacz  Did you edit the `getMessageHandler` directly? Or did you import and modify the WS engine?

**Comment by AdrKacz** [comment]
@code-leen I edited directly `getMessageHandler` in my `node_packages`.

**Comment by eliezercazares** [comment]
Can the guys at artillery merge this? I am working in a chat app and I need to verify proper message propagation. So I need to listen to emits from the server back through the opened websocket, using socket.io

**Comment by MrNocTV** [comment]
I have this issue why using the `capture`
```
Error: Callback was already called.
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:969:32
    at captured (/usr/local/lib/node_modules/artillery/core/lib/engine_ws.js:110:16)
    at /usr/local/lib/node_modules/artillery/core/lib/engine_util.js:488:16
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:473:16
    at replenish (/usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:1009:25)
    at /usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:1019:9
    at eachLimit$1 (/usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:3199:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/artillery/node_modules/async/dist/async.js:1049:16)
    at Object.captureOrMatch (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:404:9)
    at WebSocket.messageHandler (/usr/local/lib/node_modules/artillery/core/lib/engine_ws.js:68:16)
```

My code 
```
config:
    target: "wss://my_private_company/pszemraj/ballpark-trivia/alpha77d59db12d/queue/join"
    ensure:
      maxErrorRate: 1
    phases:
      - duration: 10
        arrivalRate: 5
        name: "Stress test websocket"

scenarios:
  - engine: "ws"
    flow:
      - send: 
          payload: '{"fn_index":0,"data":["Why do we wear white clothes on our wedding days?"],"session_hash":"l8tqdj2nv9"}'
          capture:
            json: "$"
            as: "test"
```

Artillery version:  `artillery@2.0.0-22`

**Pull request merged**
