### PR TITLE
fix: removed deprecated package oclif/dev-cli

### PR DESCRIPTION
**Pull request by anoopknayak**
Removing oclif/dev-cli as it's no longer supported by the authors. This is preventing from me being able to import this library within my organization.

All tests pass!

```
npm run test

> artillery@2.0.0-29 test
> export ARTILLERY_TELEMETRY_DEFAULTS='{"source":"test-suite"}' && tap --no-coverage --timeout=300 test/unit/*.test.js test/cli/*.test.js && bash test/lib/run.sh && node test/testcases/plugins/*.test.js

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
 PASS  test/unit/ssms-buckets.test.js 1 OK 9.723ms
 PASS  test/unit/dist.test.js 13 OK 10.251ms
 SKIP  test/cli/run-lambda.test.js > no tests found 226.087ms
 PASS  test/cli/command-report.test.js 1 OK 919.951ms
 PASS  test/unit/ssms-basic.test.js 5 OK 2s
test/unit/ssms-multi-process.test.js 1> [ '1675328740000' ] [ '1675328740000' ]
test/unit/ssms-multi-process.test.js 1> h p99 =====> 3905.8
test/unit/ssms-multi-process.test.js 1> control p99 ======> 3905.8
test/unit/ssms-multi-process.test.js 1> h p99 =====> 4676.2
test/unit/ssms-multi-process.test.js 1> control p99 ======> 4676.2
test/unit/ssms-multi-process.test.js 1> h p99 =====> 3984.7
test/unit/ssms-multi-process.test.js 1> control p99 ======> 3984.7
test/unit/ssms-multi-process.test.js 1> h p99 =====> 10.9
test/unit/ssms-multi-process.test.js 1> control p99 ======> 10.9
test/unit/ssms-multi-process.test.js 1> h p99 =====> 18
test/unit/ssms-multi-process.test.js 1> control p99 ======> 18
test/unit/ssms-multi-process.test.js 1> h p99 =====> 19.1
test/unit/ssms-multi-process.test.js 1> control p99 ======> 19.1
test/unit/ssms-multi-process.test.js 1> h p99 =====> 21.1
test/unit/ssms-multi-process.test.js 1> control p99 ======> 21.1
test/unit/ssms-multi-process.test.js 1> h p99 =====> 22
test/unit/ssms-multi-process.test.js 1> control p99 ======> 22
test/unit/ssms-multi-process.test.js 1> h p99 =====> 10.9
test/unit/ssms-multi-process.test.js 1> control p99 ======> 10.9
test/unit/ssms-multi-process.test.js 1> h p99 =====> 6
test/unit/ssms-multi-process.test.js 1> control p99 ======> 6
 PASS  test/unit/ssms-multi-process.test.js 63 OK 5s
 PASS  test/cli/variables-from-external-files.test.js 1 OK 5s
 PASS  test/cli/suggested-exit-codes.test.js 1 OK 6s
 PASS  test/cli/run-smoke.test.js 3 OK 6s
 PASS  test/cli/errors-and-warnings.test.js 6 OK 13s
 PASS  test/unit/before_after_hooks.test.js 8 OK 22s
 PASS  test/cli/command-run.test.js 16 OK 1m
 SKIP  TAP
 ~ test/cli/run-lambda.test.js > no tests found




  🌈 SUMMARY RESULTS 🌈

 SKIP  test/cli/run-lambda.test.js > no tests found 226.087ms

Suites:   11 passed, 1 skip, 12 of 12 completed
Asserts:  118 passed, 1 skip, of 119
Time:   1m
TAP version 13
# Subtest: util - setup
    1..0
ok 1 - util - setup # time=1.349ms

# Subtest: formatting durations
    ok 1 - Durations with one second are formatted
    ok 2 - Durations with seconds are formatted
    ok 3 - Durations with one minute are formatted
    ok 4 - Durations with minutes are formatted
    ok 5 - Durations with one hour are formatted
    ok 6 - Durations with hours are formatted
    ok 7 - Durations with one day are formatted
    ok 8 - Durations with days are formatted
    1..8
ok 2 - formatting durations # time=1.383ms

# Subtest: readArtilleryConfig
    ok 1 - Returns an empty object if .artilleryrc is not present
    ok 2 - Returns the configuration as a JSON object
    1..2
ok 3 - readArtilleryConfig # time=2.547ms

# Subtest: updateArtilleryConfig
    ok 1 - Updates the existing configuration
    ok 2 - should be equal
    1..2
ok 4 - updateArtilleryConfig # time=0.63ms

# Subtest: padded
    ok 1 - pads the space between the name and the result according to the length
    ok 2 - truncates the name when longer than the allowed length
    ok 3 - no truncating when the string length exactly matches the allowed length
    1..3
ok 5 - padded # time=0.442ms

# Subtest: util - tear down
    1..0
ok 6 - util - tear down # time=0.181ms

# Subtest: Telemetry - setup
    1..0
ok 7 - Telemetry - setup # time=5.475ms

# Subtest: Telemetry
    ok 1 - Sends telemetry data
    1..1
ok 8 - Telemetry # time=1.245ms

# Subtest: Telemetry with defaults env var
    ok 1 - Sends telemetry data
    1..1
ok 9 - Telemetry with defaults env var # time=0.612ms

# Subtest: Telemetry - disable user info through environment variable
    ok 1 - Only basic ping is sent if user opted out
    1..1
ok 10 - Telemetry - disable user info through environment variable # time=0.338ms

Telemetry data: {"event":"test event","distinctId":"artillery-core","properties":{"version":"2.0.0-29","os":"darwin","isCi":false,"$ip":null}}
# Subtest: Telemetry - debug through environment variable
    ok 1 - Telemetry data: {"event":"test event","distinctId":"artillery-core","properties":{"version":"2.0.0-29"
    1..1
ok 11 - Telemetry - debug through environment variable # time=0.762ms

# Subtest: Telemetry - teardown
    1..0
ok 12 - Telemetry - teardown # time=0.941ms

# Subtest: validate script
    1..10
    ok 1 - it should return undefined for a valid script
    # Subtest: config.target
        ok 1 - config.target should be required if config.environments is not defined
        ok 2 - it should validate the script if config.environments is defined but config.target is missing
        1..2
    ok 2 - config.target # time=1.495ms

    # Subtest: scenario flow
        ok 1 - it should return an error if "scenarios.flow" property is missing
        1..1
    ok 3 - scenario flow # time=0.536ms

    # Subtest: url
        ok 1 - it should return an error if "url" property is missing
        1..1
    ok 4 - url # time=0.415ms

    # Subtest: custom engines
        ok 1 - it should not enforce validation for scenarios with custom engines
        ok 2 - it should not enforce validation for before sections when custom engines are configured
        ok 3 - it should not enforce validation for after sections when custom engines are configured
        1..3
    ok 5 - custom engines # time=0.826ms

    # Subtest: capture
        ok 1 - it should allow capture as object
        ok 2 - it should allow capture as an array of capture objects
        ok 3 - it should return an error if capture.as is missing
        1..3
    ok 6 - capture # time=0.955ms

    # Subtest: before/after sections
        ok 1 - it should validate before sections
        ok 2 - it should fail if before.flow is not an object
        ok 3 - it should fail if after.flow is not an object
        1..3
    ok 7 - before/after sections # time=0.853ms

    # Subtest: before/after scenario hooks
        ok 1 - it allows before/after scenario hooks as strings
        ok 2 - it allows before/after scenario hooks as arrays of strings
        ok 3 - it fails if beforeScenario is not a string
        ok 4 - it fails if afterScenario is not a string
        1..4
    ok 8 - before/after scenario hooks # time=0.847ms

    # Subtest: before/after scenario hooks
        ok 1 - it allows before/after request hooks as strings
        ok 2 - it allows before/after request hooks as arrays of strings
        ok 3 - it fails if beforeRequest is not a string
        ok 4 - it fails if afterResponse is not a string
        1..4
    ok 9 - before/after scenario hooks # time=0.89ms

    # Subtest: socketio
        ok 1 - it should validate a socketio flow
        ok 2 - it should fail validation if engine is socketio and emit.channel is not a string
        1..2
    ok 10 - socketio # time=0.613ms

ok 13 - validate script # time=18.186ms

1..13
# time=119.813ms
$ /<redacted>/artillery/packages/artillery/bin/run -V

        ___         __  _ ____
  _____/   |  _____/ /_(_) / /__  _______  __ ___
 /____/ /| | / ___/ __/ / / / _ \/ ___/ / / /____/
/____/ ___ |/ /  / /_/ / / /  __/ /  / /_/ /____/
    /_/  |_/_/   \__/_/_/_/\___/_/   \__  /
                                    /____/


VERSION INFO:

Artillery: 2.0.0-29
Node.js:   v18.13.0
OS:        darwin

TAP version 13
$ ARTILLERY_PLUGIN_PATH=/<redacted>/artillery/packages/artillery/test/plugins /<redacted>/artillery/packages/artillery/bin/run run --quiet --overrides $'{"config":{"phases":[{"duration":2,"arrivalRate":2}],"target":"http://localhost:52101","processor":"/<redacted>/artillery/packages/artillery/test/testcases/plugins/processor.js","plugins":{"httphooks":{}}}}' /<redacted>/artillery/packages/artillery/test/testcases/plugins/script.json
afterResponse hook
afterResponse hook
afterResponse hook
afterResponse hook
# Subtest: plugins can attach functions to processor object
    ok 1 - plugin output
    1..1
ok 1 - plugins can attach functions to processor object # time=4920.733ms

1..1
# time=4922.92ms
```

### CODE REVIEW

**Comment by hassy** [comment]
thank you @anoopknayak! good to merge once we have the CLA - https://github.com/artilleryio/artillery/pull/1801#issuecomment-1413383426

**Comment by anoopknayak** [comment]
@hassy I'm not sure what's going on, it shows here that i haven't signed the CLA but in the CLA portal, it says I have already signed.
image

**Comment by hassy** [comment]
I think the CLA tool tries to match the email in your GitHub account with the email associated with the git commit in the PR.

You can see the email associated with the commit by running:

```
git config user.email
```

Once you add that email to your GitHub profile ([docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account)) the CLA should be recognized.

Sorry about the extra steps

**Comment by anoopknayak** [comment]
@hassy Thanks for the directions and I have updated the PR now. Please merge when you get a chance :).

**Comment by hassy** [comment]
thank you @anoopknayak!

**Comment by hassy** [comment]
@SocketSecurity ignore tap@15.2.3

**Pull request merged**
