### PR TITLE
fix: resolve dot-prop and lodash vulnerabilities

### PR DESCRIPTION
**Pull request by cmdcarini**
These updates resolve vulnerabilities present in dot-prop and lodash within this project, and resolves related issue #865 .

As a result of updating @commitlint, Husky required an upgrade as well. The changes made to the commit lint hook reflect the changes necessary as a result of this major bump. 

No core functionality has changed, and tests still pass as expected. Please advise what I should bump the version to, and if that should be done in this pull request.

### CODE REVIEW

**Comment by cmdcarini** [comment]
@hassy I think you're the one to ask for approval?

**Comment by cmdcarini** [comment]
@hassy any updates?

**Comment by dwalters-eip** [comment]
@hassy would be nice to get this merged :)

**Comment by felipeballesteros** [comment]
@hassy +1 for the merge! would help a ton ;)

**Comment by hassy** [comment]
Thank you @cmdcarini! No need to bump the version in this PR, it'll be done in a separate commit before publishing.

**Pull request merged**
