### PR TITLE
Show elapsed time when printing report to console

### PR DESCRIPTION
**Pull request by joeattardi**
Implements #589

### CODE REVIEW

**Comment by joeattardi** [comment]
Not sure why the Travis CI build failed - the errors don't seem related to any of the code that I changed. Anyone have any ideas?

**Comment by hassy** [comment]
Not sure @joeattardi but I'll investigate. Thanks for the PR!

**Comment by joeattardi** [comment]
Looks like it doesn't like the object spread syntax in version 4.0.1 of `csv-parse`:

https://github.com/adaltas/node-csv-parse/compare/v4.0.1...master#diff-6d186b954a58d5bb740f73d84fe39073R35

**Comment by hassy** [comment]
Yeah, which is unexpected since the commit (https://github.com/artilleryio/artillery/commit/04b1fcdf660971c447a991c1cedf3c4b0f91b60d) in which csv-parse was upgraded passed its tests.

**Comment by hassy** [comment]
@joeattardi this will be fixed once #593 is working & merged; we need to update the version of Node.js used on Travis, and the problem wasn't caught earlier because `package-lock.json` was out of date.

**Comment by hassy** [comment]
thanks @joeattardi!

**Pull request merged**
