### PR TITLE
Fix #1027: Don't fail capture on false boolean values

### LINKED ISSUE #1027: Version 1.7.0 Breaks Boolean Capture
I have this step that uses the artillery expect plugin and passes in version 1.6.2, but fails in 1.7.0.

```
- post:
        url: '/verify/reset?email=success@simulator.amazonses.com'
        headers:
          password: 5f4dcc3b5aa765d61d8327deb882cf99
        auth:
          user: application
          pass: secret
        capture:
          - json: $.email.address
            as: email
          - json: $.email.verified
            as: verified
        expect:
          - statusCode: 200
          - hasProperty: creationTime
          - hasProperty: lastUpdateTime
          - equals:
              - "{{ email }}"
              - "success@simulator.amazonses.com"
          - equals:
              - "{{ verified }}"
              - false
```

It's failing with this error:

```
not ok equals true, false
  expected: all values to be equal
       got: true, false
  Request params:
    http://localhost:8080/verify/reset?email=success@simulator.amazonses.com
    ""
  Headers:
   date : Wed, 12 May 2021 22:33:46 GMT
   content-type : application/json
   content-length : 254
  Body:
    "{\"email\":{\"address\":\"success@simulator.amazonses.com\",\"verified\":false,\"verificationToken\":null},\"password\":\"5f4dcc3b5aa765d61d8327deb882cf99\",\"attributes\":[\"hello\",\"world\"],\"creationTime\":1620858825642,\"uniqueID\":\"ABC123\",\"lastUpdateTime\":1620858826475}"
  User variables:
     target : http://localhost:8080
     $environment : undefined
     testMetrics : false
     $uuid : ccc8885d-e7d1-4038-b533-1b1f83083dcb
     email : success@simulator.amazonses.com
     creationOriginal : 1620858825642
     errorString : Unable to validate user with provided credentials. (User: success@simulator.amazonses.com)
     creationGet : 1620858825642
     verificationToken : c7bebcfc-89cd-4a98-91bb-343587572a8e
     verified : true
```

It looks like the capture here is not working correctly:

```
- json: $.email.verified
  as: verified
```

Because the JSON body has `verified` set to false, but artillery thinks it is set to true.

### LINKED ISSUE #1040: Matching false always succeed
I am trying to use socketio engine with artillery. My custom scenario requires acknowledge to be of type `{ status: false, data: ... }`. Even though socketio server replies with `{ status: true }`, no error is thrown. Same applies for all the falsy values of javascript.

```yaml
config:
  target: "http://localhost:3000/"
  socketio:
    transports: ["websocket"]
  phases:
    - duration: 1
      arrivalRate: 4
      maxVusers: 4

scenarios:
  - name: Test
    flow:
      - emit:
          channel: "custom_event"
          data: "{}"
          acknowledge:
            match:
              json: "$.0.status"
              value: false
```

### PR DESCRIPTION
**Pull request by RohanNagar**
Closes #1027

### CODE REVIEW

**Comment by mkadirtan** [comment]
> Closes #1027 and closes #1040.

No, this PR doesn't close #1040 . You can check #1041 , the problem with #1040 is when using captureOrMatch

**Comment by RohanNagar** [comment]
Got it, updated the description.

**Comment by hassy** [comment]
Nice! Could you update the commit message to follow the existing convention? Something like `fix: don't fail capture on false boolean values`. That's the step that's failing on CirlceCI right now.

(You can edit the commit message with `git commit --amend` in your branch, then `git push --force` to your branch to overwrite)

**Comment by RohanNagar** [comment]
@hassy fixed! The build passes now.

**Comment by hassy** [comment]
Nice! 🎉

**Comment by RohanNagar** [comment]
@hassy I noticed the latest release (1.7.3) doesn't include this fix - would you be able to include it in the next release? Thank you!

**Comment by RohanNagar** [comment]
@hassy any update on this?

**Comment by hassy** [comment]
@RohanNagar the commit has been backported to the v1.7 branch now and will be rolled out in the next v1.7 release (most likely tomorrow)

**Pull request merged**
